from django.conf.urls import patterns, url



from twipymap.views.location_views import *
urlpatterns = patterns('',
    url(
        regex=r'^location/archive/$',
        view=LocationArchiveIndexView.as_view(),
        name='twipymap_location_archive_index'
    ),
    url(
        regex=r'^location/create/$',
        view=LocationCreateView.as_view(),
        name='twipymap_location_create'
    ),
    url(
        regex=r'^location/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=LocationDateDetailView.as_view(),
        name='twipymap_location_date_detail'
    ),
    url(
        regex=r'^location/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=LocationDayArchiveView.as_view(),
        name='twipymap_location_day_archive'
    ),
    url(
        regex=r'^location/(?P<pk>\d+?)/delete/$',
        view=LocationDeleteView.as_view(),
        name='twipymap_location_delete'
    ),
    url(
        regex=r'^location/(?P<pk>\d+?)/$',
        view=LocationDetailView.as_view(),
        name='twipymap_location_detail'
    ),
    url(
        regex=r'^location/$',
        view=LocationListView.as_view(),
        name='twipymap_location_list'
    ),
    url(
        regex=r'^location/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=LocationMonthArchiveView.as_view(),
        name='twipymap_location_month_archive'
    ),
    url(
        regex=r'^location/today/$',
        view=LocationTodayArchiveView.as_view(),
        name='twipymap_location_today_archive'
    ),
    url(
        regex=r'^location/(?P<pk>\d+?)/update/$',
        view=LocationUpdateView.as_view(),
        name='twipymap_location_update'
    ),
    url(
        regex=r'^location/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=LocationWeekArchiveView.as_view(),
        name='twipymap_location_week_archive'
    ),
    url(
        regex=r'^location/archive/(?P<year>\d{4})/$',
        view=LocationYearArchiveView.as_view(),
        name='twipymap_location_year_archive'
    ),
)


from twipymap.views.contact_views import *
urlpatterns += patterns('',
    url(
        regex=r'^contact/archive/$',
        view=ContactArchiveIndexView.as_view(),
        name='twipymap_contact_archive_index'
    ),
    url(
        regex=r'^contact/create/$',
        view=ContactCreateView.as_view(),
        name='twipymap_contact_create'
    ),
    url(
        regex=r'^contact/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=ContactDateDetailView.as_view(),
        name='twipymap_contact_date_detail'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=ContactDayArchiveView.as_view(),
        name='twipymap_contact_day_archive'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/delete/$',
        view=ContactDeleteView.as_view(),
        name='twipymap_contact_delete'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/$',
        view=ContactDetailView.as_view(),
        name='twipymap_contact_detail'
    ),
    url(
        regex=r'^contact/$',
        view=ContactListView.as_view(),
        name='twipymap_contact_list'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=ContactMonthArchiveView.as_view(),
        name='twipymap_contact_month_archive'
    ),
    url(
        regex=r'^contact/today/$',
        view=ContactTodayArchiveView.as_view(),
        name='twipymap_contact_today_archive'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/update/$',
        view=ContactUpdateView.as_view(),
        name='twipymap_contact_update'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=ContactWeekArchiveView.as_view(),
        name='twipymap_contact_week_archive'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/$',
        view=ContactYearArchiveView.as_view(),
        name='twipymap_contact_year_archive'
    ),
)
